### ISSUE TITLE
新注册用户无法登录？

### ISSUE THREAD

**Issue by Jiang1206** [one-ccs/leave_approval_management_sys#2]
项目到本地后，运行很顺利，但是怎么登录呢？自己建立的用户一致密码错误

**Comment by one-ccs** [comment]
你好，首先感谢使用本程序，并提供反馈。

我已经拉取仓库，并运行、注册、登录成功了。
请在网页中注册，因为注册的密码会先加密再存储进入数据库，若明文修改数据库是无法登录的。

如果本仓库对你有用，不要忘记右上角 Star 哦，这是对作者最大的鼓励。
