### ISSUE TITLE
没有login.html文件？

### ISSUE THREAD

**Issue by Keyu30Zhang** [one-ccs/leave_approval_management_sys#3]
你好，app.py中有login函数涉及到了login.html，但是模板中好像没有这个html

**Comment by one-ccs** [comment]
你好，首先感谢使用本程序，并提供反馈。

该项目的登录页面为 session.html，位于 www/templates/session.html，请知悉。

如果本仓库对你有用，不要忘记右上角 Star 哦，这是对作者最大的鼓励。
